<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ay_cpp</name>  <!-- コピペ -->
  <version>0.0.0</version>  <!-- コピペ -->
  <description>The ay_cpp package</description>  <!-- コピペ -->
  <author email="dummy@dummy.com">FingerVision Inc.</author>  <!-- 社名にする。email属性は会社の代表連絡先がないので記載していない(属性の記載は必須) -->
  <maintainer email="dummy@dummy.com">FingerVision Inc.</maintainer>  <!-- 社名にする。email属性は会社の代表連絡先がないので記載していない(属性の記載は必須) -->
  <license>GPL-3.0-only</license>  <!--<license>Proprietary</license>-->  <!-- ←を設定したいが，ライセンスの関係でできていない -->

  <buildtool_depend>ament_cmake</buildtool_depend>  <!-- <buildtool_depend>catkin</buildtool_depend> に対応 -->

  <build_depend>rclcpp</build_depend>  <!-- <depend>roscpp</depend> に対応 -->
  <exec_depend>rclcpp</exec_depend>  <!-- <depend>roscpp</depend> に対応 -->

  <test_depend>ament_lint_auto</test_depend>  <!-- 汎用テスト設定 -->
  <test_depend>ament_lint_common</test_depend>  <!-- 汎用テスト設定 -->
  <test_depend>ament_cmake_gtest</test_depend>  <!-- 汎用テスト設定 -->
  <test_depend>ament_cmake_ros</test_depend>  <!-- launchテスト用，テスト実行時に ament_cmake_ros (の中の add_launch_test) が必要 -->
  <test_depend>launch_testing_ros</test_depend>  <!-- launchテスト用，launchファイルを動かすための依存 -->
  <test_depend>rclcpp</test_depend>  <!-- 汎用テスト設定, <depend>roscpp</depend> に対応 -->

  <export>
    <build_type>ament_cmake</build_type>  <!-- 汎用出力設定 -->
  </export>
</package>
